// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkWGjTdpSZCfun277mVcYt08a_zq4SUGk',
    appId: '1:1061169467404:web:dce896df2c78e190e7de29',
    messagingSenderId: '1061169467404',
    projectId: 'gpss-fe7d9',
    authDomain: 'gpss-fe7d9.firebaseapp.com',
    databaseURL:
        'https://gpss-fe7d9-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'gpss-fe7d9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnCrWDrWuU7LUi19pmAmQNuahXyZBiQvw',
    appId: '1:1061169467404:android:add4be2e06f631c6e7de29',
    messagingSenderId: '1061169467404',
    projectId: 'gpss-fe7d9',
    databaseURL:
        'https://gpss-fe7d9-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'gpss-fe7d9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXca-6vaQLipYwcqfNYGScc_z1W9CJVbc',
    appId: '1:1061169467404:ios:7c2f3eb3b699210ce7de29',
    messagingSenderId: '1061169467404',
    projectId: 'gpss-fe7d9',
    databaseURL:
        'https://gpss-fe7d9-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'gpss-fe7d9.appspot.com',
    iosBundleId: 'com.example.colorSensor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXca-6vaQLipYwcqfNYGScc_z1W9CJVbc',
    appId: '1:1061169467404:ios:7c2f3eb3b699210ce7de29',
    messagingSenderId: '1061169467404',
    projectId: 'gpss-fe7d9',
    databaseURL:
        'https://gpss-fe7d9-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'gpss-fe7d9.appspot.com',
    iosBundleId: 'com.example.colorSensor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkWGjTdpSZCfun277mVcYt08a_zq4SUGk',
    appId: '1:1061169467404:web:b72b435a2ddca965e7de29',
    messagingSenderId: '1061169467404',
    projectId: 'gpss-fe7d9',
    authDomain: 'gpss-fe7d9.firebaseapp.com',
    databaseURL:
        'https://gpss-fe7d9-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'gpss-fe7d9.appspot.com',
  );
}
